# Generated by Django 6.0.5 on 2026-06-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(default='Action', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
